### ISSUE TITLE
Enzo Editor, Splits and Trails

### ISSUE THREAD

**Issue by ElliotGarbus** [francoisgeorgy/enzo-web-editor#1]
Francois,
I want to share I've found the following issues with Splits and Trails on the Enzo.  I was curious if you have seen the same.

Eratta: Trails and split values 1,2,3 can not be written via midi.  They must be set on the Enzo using the alt button as described in the Enzo manual.  These values can be read via MIDI.

Eratta:  if SPLIT is ON, TRAILS are ON.  There is no setting where SPLIT is on and TRAILS are off.

I've also written and Enzo Editor:  [https://github.com/ElliotGarbus/Enzo-Editor-and-Librarian](url)

**Comment by francoisgeorgy** [comment]
Hi Elliot,

I saw your editor. Unfortunately I don't have a Windows box so I could not try it. 

I have the same issue as you with split and trails. I asked Meris and here is their answer:

"Although it you can edit most Globals over Sysex, you cannot remotely edit the Trails setting on the Enzo over Sysex.   This is specific to Enzo."

So, I think there's no solution. Maybe one day Meris will release a firmware update.

Best regards
