### ISSUE TITLE
Virtual knobs will not actualize their states when switching presets.

### ISSUE THREAD

**Issue by Pick707** [francoisgeorgy/enzo-web-editor#13]
Hi François,
First of all thanks for your amazing and very useful work in editor department, all musicians should be gratefull !!
On the demo video of the Enzo Meris editor (YouTube) I see that when you select a preset the knobs settings reflect immediately their positions in that specific preset. When I use the editor everything work perfect except this feature. The MIDI communication work in both sides (from Enzo to editor and from editor to enzo), if I move knobs on the Enzo then knobs on the editor move and vice versa but when I activate different presets from Enzo or in the editor itself the state of the virtual knobs don't change at all (the sounds change accordingly thought)... Any clue? Thanks for your help! 

Many Thanks! :)
Pierre

**Comment by francoisgeorgy** [comment]
Hi Pierre,

Thanks a lot for your feedback.

My family and I just moved in a new appartement and I still have most of my homestudio in boxes. So, you will have to wait a couple of days before I'm able to test and reproduce the problem you are observing.

When you say "when I activare different presets from the Enzo", how do you do that? 

Thanks for your patience.

Kind regards

**Comment by Pick707** [comment]
Hi François,

Thanks for your support and take your time, moving is a difficult thing! ;)
When I say that I activate presets I mean from my MIDI BABY 3 and also from
your app. When I select preset 1-2-3......16 from my Midi Baby or from the
app the sounds change accordingly when I play the guitar but the problem is
that there is absolutely no change on the knobs in the app. The knobs don't
reflect the preset switching. But I suspect that it has something to do
with my setup because it does the same thing with another Enzo editor I
tried... As I said when I turn knobs on the Enzo the knobs in the app will
move accordingly and when I move the knobs in the app the Enzo responds
accordingly too. So it seems that the communication is ok on bothy sides.

Take care!

Pierre

Le lun. 5 avr. 2021 à 02:16, François Georgy ***@***.***> a
écrit :

**Comment by Pick707** [comment]
I suspect that this issue is on the Midi Baby 3 firmware part. For the
moment the firmware 8d does not work for this and the problem should be
resolved in the 8e version which should come soon... I hope!.

Le lun. 5 avr. 2021 à 02:16, François Georgy ***@***.***> a
écrit :

**Comment by Pick707** [comment]
Hi François,

I just got the latest beta firmware for my Midi Baby 3 and it does not
resolve the issue. It is still the same... Any clue? Take your time! :)
Thanks!

Le lun. 5 avr. 2021 à 02:16, François Georgy ***@***.***> a
écrit :

**Comment by francoisgeorgy** [comment]
Hi Pierre,

Parlez-vous français?

I also have a MIDI Baby. I'll have a look as soon as possible. But I'm still waiting on a new desk before I can re-install my little homestudio. Thanks for your patience and understanding.

Kind regards
François

**Comment by Pick707** [comment]
Oui je parle français! Merci pour votre support! Je serai patient! :) Et si
j'arrive à résoudre le problème dans l'intervalle je vous le ferai savoir.
Pierre

Le lun. 5 avr. 2021 à 15:45, François Georgy ***@***.***> a
écrit :

**Comment by Pick707** [comment]
Tout fonctionne bien maintenant. Il semble que j'aurais mal installé le
nouveau beta firmware 8e la première fois... J'ai donc utilisé un autre
ordinateur pour le deuxième essai et maintenant tout fonctionne à
merveille! :) Merci pour votre aide et bon déménagement! :) Pierre

Le lun. 5 avr. 2021 à 15:45, François Georgy ***@***.***> a
écrit :

**Comment by francoisgeorgy** [comment]
Super. Merci pour cette bonne nouvelle.

Meilleures salutations
