### ISSUE TITLE
Hedra Editor in the making...?

### ISSUE THREAD

**Issue by mayasfinest** [francoisgeorgy/enzo-web-editor#26]
Hi François,
i just stumbled upon your Meris Editors and absolutely love them, thank you so much!
As I own 4 Meris pedals (Polymoon, Hedra, Mercury7 and  Enzo) these are for sure super helpful.
On your studiocode.dev site you advertise an upcoming (2021) Hedra editor…
Are you still working on it? I would love to lay hands on it 😉

Thanks
Jörg

PS: Sorry i opened up an "issue" here, there is no issue, in fact it's a real pleasure ;-)

**Comment by francoisgeorgy** [comment]
Hi Jörg,

I replied to your email.

For other how may read this issue : I don't know when the Hedra will be ready. I don't own a Hedra myself (yet) and I don't have a lot of time to work on my editors at the moment. However I still hope to have the time to release this editor before this summer.

Thanks for your patience and understanding.
